seed_everything: 333
trainer:
  gpus: [0]
  gradient_clip_val: 1.0
  default_root_dir: &exp_name results/MH_retriever
  val_check_interval: 1.0
  max_epochs: &max_epochs 5
  log_every_n_steps: 50
  logger:
    - class_path: lightning_modules.patches.patched_loggers.PatchedWandbLogger
      init_args:
        entity: yilunzhao
        project: mh_retriever
        name: *exp_name
        log_model: False
        save_code: True
        offline: True
  callbacks:
    - class_path: pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        filename: '{step}-{val_loss:.4f}_new'
        save_top_k: 3
    - class_path: pytorch_lightning.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: pytorch_lightning.callbacks.progress.TQDMProgressBar
      init_args:
        refresh_rate: 1
        
  accelerator: gpu
  strategy: ddp
  accumulate_grad_batches: 2

model:
  class_path: lightning_modules.models.new_retriever_model.RetrieverModel
  init_args:
    transformer_model_name: &transformer ProsusAI/finbert
    topn: 10
    dropout_rate: 0.1
    optimizer:
      init_args: 
        lr: 2.0e-5
        betas: 
          - 0.9
          - 0.999
        eps: 1.0e-8
        weight_decay: 0.1
    lr_scheduler:
      name: linear
      init_args:
        num_warmup_steps: 100
        num_training_steps: 10000

data:
  class_path: lightning_modules.datasets.new_retriever_reader.RetrieverDataModule
  init_args:
    transformer_model_name: *transformer
    batch_size: 24
    val_batch_size: 24
    num_workers: 8
    train_file_path: dataset/dev.json
    val_file_path: dataset/dev.json
    train_inventory_file_path: dataset/dev_inventory.csv
    dev_inventory_file_path: dataset/dev_inventory.csv
    train_max_instances: -1
    val_max_instances: -1

# clear; export PYTHON PATH=`pwd`; python trainer.py fit --config training_configs/retriever_finetuning.yaml
